// SvelteNotes/src/lib/Header.svelte
<header class="header">
  <img alt="Svelte logo" src="/svelte.svg" class="header-logo"/>
  <div class="header-content">
    <h1 class="header-title">Svelte Notes</h1>
    <p>Learning Svelte from <a href="https://learn.svelte.dev/" target="_blank">learn.svelte.dev</a>.</p>
  </div>
</header>

<style>
  .header {
    display: flex;
    flex-direction: row;
    padding: 6rem 2rem;
    max-width: 60rem;
  }

  .header-logo {
    width: 80px;
    margin-right: 20px;
  }

  .header-content {
    margin-right: 30px;
    flex-direction: column;
  }

  .header-title {
    font-weight: bold;
  }
</style>

// React/src/Header.jsx
import "./Header.css"

export default function Header() {
  return (
    <header className="header">
      <img alt="React logo" src="react.svg" className="header-logo"/>
      <div className="header-content">
        <h1 className="header-title">React Notes</h1>
        <p>Learning React from <a href="https://react.dev/learn" target="_blank">react.dev/learn</a>.</p>
      </div>
    </header>
  )
}
